As/ginger algebra ocl
HorizenOfficial/zend_oo pull request #102
Opened 2021-03-26 13:55 UTC by alsala

Integration with mc crypto lib supporting cctp lib

2021-03-30 13:25 UTC, nastenko approved these changes
All CommitmentTree-related methods look consistent with specification and Rust implementation

2021-05-13 10:14 UTC, albertog78 requested changes

2021-05-13 10:14 UTC, albertog78 commented on src/primitives/transaction.cpp
> +    ptr[SC_FIELD_SIZE-1] &= 0x3f;
calculate scId in CCTP lib using poseidon hash

2021-06-30 08:47 UTC, ptagl commented
This PR is now obsolete.

2021-06-30 08:47 UTC, closed without merging