Backport zen 2.0.23 to zendoo
HorizenOfficial/zend_oo pull request #103
Opened 2021-04-02 13:17 UTC by abi87

Built on top of Backport zen 2.0.22 to zendoo PR https://github.com/HorizenOfficial/zend_oo/pull/72

2021-04-02 13:21 UTC, abi87 commented on doc/man/zen-tx.1
> +.TH ZEN-TX "1" "July 2021" "zen-tx v2.1.0-beta4" "User Commands"
Should be March 2021, I missed to modify the month by mistake. I won't bother changing it anyhow since this should be all overwritten upon release

2021-04-22 13:39 UTC, alsala requested changes

2021-04-22 13:39 UTC, alsala commented on src/rpc/misc.cpp
> -            obj.pushKV("pubkeyhash", keyID.ToString());
This should be retained, it was added in commit d26b937b76d74ee55ef6c83469c83ae8a625ab1d

2021-04-22 14:25 UTC, alsala approved these changes

2021-04-22 14:25 UTC, alsala commented on src/rpc/misc.cpp
> -            obj.pushKV("pubkeyhash", keyID.ToString());
done

2021-06-14 14:47 UTC, closed without merging