Cert submitter optimization(Draft)
HorizenOfficial/zend_oo pull request #116
Opened 2021-05-18 08:43 UTC by VolodymyrBabaiev

2021-05-18 09:00 UTC, VolodymyrBabaiev commented
Mainchain part for resolving the issue from sidechain https://github.com/HorizenOfficial/Sidechains-SDK/issues/256
Also contain the fixes for https://github.com/HorizenOfficial/zend_oo/issues/114 (doesn't have tests).

2021-05-21 08:10 UTC, vovanloc0798 approved these changes

2021-06-02 09:00 UTC, i-Alex commented on src/zen/websocket_server.cpp
> +                mempoolTopQualityCert.push_back(Pair("fee", topQualCert.mainchainBackwardTransferRequestScFee));
Mempool Cert fee is different. Fees are the coins amount diff between inputs and outputs.
There is an info about cert fees in the mempool.

2021-06-04 06:33 UTC, VolodymyrBabaiev commented on qa/rpc-tests/ws_messages.py
> +        assert_equal({}, mempool_cert_)
Done.

2021-06-04 06:33 UTC, VolodymyrBabaiev commented on src/zen/websocket_server.cpp
> +                CScCertificate topQualCert;
Done.

2021-06-04 08:23 UTC, i-Alex approved these changes

2021-06-07 11:51 UTC, i-Alex approved these changes

2021-06-09 07:24 UTC, i-Alex requested changes

2021-06-09 07:24 UTC, i-Alex commented on src/zen/websocket_server.cpp
> +        rspPayload.push_back(Pair("mempool_top_quality_cert", mempoolCert));
let's use CamelCase names as in other places:
`mempool_top_quality_cert` -> `mempoolTopQualityCert`
`chain_top_quality_cert` -> `chainTopQualityCert`

2021-06-10 10:52 UTC, alsala requested changes

2021-06-10 10:52 UTC, alsala commented on src/zen/websocket_server.cpp
> +                        chainTopQualityCert.push_back(Pair("rawCertificateHex", certHex));
Just for symmetry with mempool, should we need the fee in the json obj we could use the view obj for getting it from the cert, for instance:
   certFee = topQualCert.GetFeeAmount(view.GetValueIn(topQualCert));

2021-06-11 06:25 UTC, VolodymyrBabaiev commented on src/zen/websocket_server.cpp
> +                CScCertificate topQualCert;
Done.

2021-06-16 16:29 UTC, alsala approved these changes

2021-06-17 09:29 UTC, i-Alex approved these changes

2021-06-22 09:12 UTC, albertog78 requested changes

2021-06-22 09:12 UTC, albertog78 commented on src/zen/websocket_server.cpp
> +                    chainTopQualityCert.push_back(Pair("quality", topQualityCertQuality));
return also as a separate field the certificate referenced epoch (we have to be sure on sidechain side that the last received certificate doesn't belong to the previous epoch)
Do the same for mempool cert

2021-06-24 07:29 UTC, i-Alex approved these changes

2021-07-20 09:26 UTC, albertog78 approved these changes

2021-07-20 09:26 UTC, merged