As/issue 95
HorizenOfficial/zend_oo pull request #126
Opened 2021-06-11 15:50 UTC by alsala

Fix and py test for issue #95: added csw input to CreateTransaction wallet function in order to handle properly csw in the fundrawtransaction cmd

2021-06-14 09:45 UTC, i-Alex requested changes

2021-06-14 09:45 UTC, i-Alex commented on src/wallet/wallet.cpp
> +                // add csw input
See the code above related to the `mempooltxinputlimit` check. We should consider CSW inputs as well.

2021-06-15 08:59 UTC, i-Alex approved these changes

2021-06-18 10:06 UTC, ptagl approved these changes

2021-06-23 15:51 UTC, merged