Added a check than no more than a fixed number of csw input can be ac…
HorizenOfficial/zend_oo pull request #168
Opened 2021-08-02 16:59 UTC by alsala

…cepted in the mempool for a SC

2021-08-03 09:07 UTC, i-Alex reviewed
Fine for me. Will accept after tests updates.

2021-08-03 10:55 UTC, ptagl requested changes

2021-08-03 10:55 UTC, ptagl commented on qa/rpc-tests/sc_csw_eviction_from_mempool.py
> +from test_framework.mc_test.mc_test import *
I would avoid importing unused symbols.

```suggestion
from test_framework.mc_test.mc_test import CertTestUtils, CSWTestUtils, generate_random_field_element_hex
```

2021-08-03 10:55 UTC, ptagl commented on qa/rpc-tests/sc_csw_eviction_from_mempool.py
> +            assert(false)
Typo, `false` is not defined.

```suggestion
            assert(False)
```

2021-08-03 10:55 UTC, ptagl commented on qa/rpc-tests/sc_csw_eviction_from_mempool.py
> +            assert(false)
Typo, `false` is undefined.

```suggestion
            assert(False)
```

2021-08-03 16:42 UTC, ptagl approved these changes

2021-08-03 16:51 UTC, alsala commented on qa/rpc-tests/sc_csw_eviction_from_mempool.py
> +from test_framework.mc_test.mc_test import *
Done

2021-08-03 16:52 UTC, alsala commented on qa/rpc-tests/sc_csw_eviction_from_mempool.py
> +            assert(false)
Done

2021-08-03 16:52 UTC, alsala commented on qa/rpc-tests/sc_csw_eviction_from_mempool.py
> +            assert(false)
Done

2021-08-04 07:22 UTC, i-Alex approved these changes

2021-08-30 14:46 UTC, albertog78 approved these changes

2021-08-30 14:47 UTC, merged