Updating RPC calls
HorizenOfficial/zend_oo pull request #199
Opened 2021-10-01 08:55 UTC by VolodymyrBabaiev

Resolved issues #157, #158, #159, #160, #161 

Removed obsolete version of sc_create, sc_send, sc_sendmany.
Removed decoderawsertificate and getrawcertificate.
Added fromAddress to sc_send_certificate RPC call.

2021-10-01 14:37 UTC, i-Alex requested changes

2021-10-01 14:37 UTC, i-Alex commented on src/wallet/rpcwallet.cpp
> +            " 9. fromAddress                     (string, required) The address UTXO will be taken from\n"
why `fromAddress` is `required`. I guess it should be `optional`

2021-10-01 14:37 UTC, i-Alex commented on src/wallet/rpcwallet.cpp
> +            "10. fee                             (numeric, optional, default=" + strprintf("%s", FormatMoney(SC_RPC_OPERATION_DEFAULT_MINERS_FEE)) + ") The fee of the certificate in ZEN\n"
update `sc_send_certificate` non-string args indexes in `rpc/client.cpp`

2021-10-05 15:38 UTC, ptagl approved these changes

2021-11-08 16:05 UTC, closed without merging