Websocket optimization
HorizenOfficial/zend_oo pull request #56
Opened 2020-10-27 10:50 UTC by VolodymyrBabaiev

In order to improve performance(SC creates too many block request when it far beyond the MC) get_block_headers websocket request was implemented. It allows SC to retrieve up to 50 block headers from MC in one requests.

2020-10-28 15:46 UTC, abi87 commented
Following backport of sidechain_testnet to sidechain_dev, I changed back and forth target branch to refresh/rebase the PR

2020-11-02 07:15 UTC, i-Alex requested changes

2020-11-02 10:10 UTC, alsala commented on src/zen/websocket_server.cpp
> +    void sendBlockHeaders(UniValue headers, WsEvent::WsMsgType msgType, std::string clientRequestId = "")
'UniValue headers' could be made 'const UniValue& headers' in order not to copy the input object

2020-11-02 10:22 UTC, alsala commented on src/zen/websocket_server.cpp
> +        ss << block.GetBlockHeader();
The analogous GetBlockHeader() could be called also on pindex ptr directly, without reading the block from disk

2021-02-12 14:04 UTC, i-Alex approved these changes

2021-05-07 13:47 UTC, albertog78 approved these changes

2021-05-07 13:47 UTC, merged